vim.g.mapleader = " "

local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
  vim.fn.system({
    "git",
    "clone",
    "--filter=blob:none",
    "https://github.com/folke/lazy.nvim.git",
    "--branch=stable", -- latest stable release
    lazypath,
  })
end
vim.opt.rtp:prepend(lazypath)
require("lazy").setup("plugins", {
  change_detection = {
    notify = false,
  },
  dev = {
    path = "~/code/mrWinston",
  },
})

require("plugins")
require("mappings")
require("config")
require("tools.install").installAll()


-- remote plugs:

vim.cmd([[
if exists('g:loaded_go_nvim_test')
    finish
endif
let g:loaded_go_nvim_test = 1

function! s:Requirehello(host) abort
    " 'hello' is the binary created by compiling the program above.
    return jobstart(['go-nvim-test'], {'rpc': v:true})
endfunction

call remote#host#Register('go-nvim-test', 'x', function('s:Requirehello'))
" The following lines are generated by running the program
" command line flag --manifest hello
call remote#host#RegisterPlugin('go-nvim-test', '0', [
\ {'type': 'function', 'name': 'Hello', 'sync': 1, 'opts': {}},
\ {'type': 'function', 'name': 'ShowTodos', 'sync': 1, 'opts': {}},
\ ])
]])
