require"octo".setup({
  use_local_fs = true,                    -- use local files on right side of reviews
  mappings_disable_default = false,        -- disable default mappings if true, but will still adapt user mappings
  mappings = {
    runs = {
      expand_step = { lhs = "o", desc = "expand workflow step" },
      open_in_browser = { lhs = "<C-b>", desc = "open workflow run in browser" },
      refresh = { lhs = "<C-r>", desc = "refresh workflow" },
      rerun = { lhs = "<C-o>", desc = "rerun workflow" },
      rerun_failed = { lhs = "<C-f>", desc = "rerun failed workflow" },
      cancel = { lhs = "<C-x>", desc = "cancel workflow" },
      copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
    },
    issue = {
      close_issue = { lhs = "<localleader>oic", desc = "close issue" },
      reopen_issue = { lhs = "<localleader>oio", desc = "reopen issue" },
      list_issues = { lhs = "<localleader>oil", desc = "list open issues on same repo" },
      reload = { lhs = "<C-r>", desc = "reload issue" },
      open_in_browser = { lhs = "<C-b>", desc = "open issue in browser" },
      copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
      add_assignee = { lhs = "<localleader>oaa", desc = "add assignee" },
      remove_assignee = { lhs = "<localleader>oad", desc = "remove assignee" },
      create_label = { lhs = "<localleader>olc", desc = "create label" },
      add_label = { lhs = "<localleader>ola", desc = "add label" },
      remove_label = { lhs = "<localleader>old", desc = "remove label" },
      goto_issue = { lhs = "<localleader>ogi", desc = "navigate to a local repo issue" },
      add_comment = { lhs = "<localleader>oca", desc = "add comment" },
      add_reply = { lhs = "<localleader>ocr", desc = "add reply" },
      delete_comment = { lhs = "<localleader>ocd", desc = "delete comment" },
      next_comment = { lhs = "]c", desc = "go to next comment" },
      prev_comment = { lhs = "[c", desc = "go to previous comment" },
      react_hooray = { lhs = "<localleader>orp", desc = "add/remove 🎉 reaction" },
      react_heart = { lhs = "<localleader>orh", desc = "add/remove ❤️ reaction" },
      react_eyes = { lhs = "<localleader>ore", desc = "add/remove 👀 reaction" },
      react_thumbs_up = { lhs = "<localleader>or+", desc = "add/remove 👍 reaction" },
      react_thumbs_down = { lhs = "<localleader>or-", desc = "add/remove 👎 reaction" },
      react_rocket = { lhs = "<localleader>orr", desc = "add/remove 🚀 reaction" },
      react_laugh = { lhs = "<localleader>orl", desc = "add/remove 😄 reaction" },
      react_confused = { lhs = "<localleader>orc", desc = "add/remove 😕 reaction" },
    },
    pull_request = {
      checkout_pr = { lhs = "<localleader>opo", desc = "checkout PR" },
      merge_pr = { lhs = "<localleader>opm", desc = "merge commit PR" },
      squash_and_merge_pr = { lhs = "<localleader>opsm", desc = "squash and merge PR" },
      rebase_and_merge_pr = { lhs = "<localleader>oprm", desc = "rebase and merge PR" },
      merge_pr_queue = { lhs = "<localleader>opq", desc = "merge commit PR and add to merge queue (Merge queue must be enabled in the repo)" },
      squash_and_merge_queue = { lhs = "<localleader>opsq", desc = "squash and add to merge queue (Merge queue must be enabled in the repo)" },
      rebase_and_merge_queue = { lhs = "<localleader>oprq", desc = "rebase and add to merge queue (Merge queue must be enabled in the repo)" },
      list_commits = { lhs = "<localleader>opc", desc = "list PR commits" },
      list_changed_files = { lhs = "<localleader>opf", desc = "list PR changed files" },
      show_pr_diff = { lhs = "<localleader>opd", desc = "show PR diff" },
      add_reviewer = { lhs = "<localleader>ova", desc = "add reviewer" },
      remove_reviewer = { lhs = "<localleader>ovd", desc = "remove reviewer request" },
      close_issue = { lhs = "<localleader>oic", desc = "close PR" },
      reopen_issue = { lhs = "<localleader>oio", desc = "reopen PR" },
      list_issues = { lhs = "<localleader>oil", desc = "list open issues on same repo" },
      reload = { lhs = "<C-r>", desc = "reload PR" },
      open_in_browser = { lhs = "<C-b>", desc = "open PR in browser" },
      copy_url = { lhs = "<C-y>", desc = "copy url to system clipboard" },
      goto_file = { lhs = "gf", desc = "go to file" },
      add_assignee = { lhs = "<localleader>oaa", desc = "add assignee" },
      remove_assignee = { lhs = "<localleader>oad", desc = "remove assignee" },
      create_label = { lhs = "<localleader>olc", desc = "create label" },
      add_label = { lhs = "<localleader>ola", desc = "add label" },
      remove_label = { lhs = "<localleader>old", desc = "remove label" },
      goto_issue = { lhs = "<localleader>ogi", desc = "navigate to a local repo issue" },
      add_comment = { lhs = "<localleader>oca", desc = "add comment" },
      add_reply = { lhs = "<localleader>ocr", desc = "add reply" },
      delete_comment = { lhs = "<localleader>ocd", desc = "delete comment" },
      next_comment = { lhs = "]c", desc = "go to next comment" },
      prev_comment = { lhs = "[c", desc = "go to previous comment" },
      react_hooray = { lhs = "<localleader>orp", desc = "add/remove 🎉 reaction" },
      react_heart = { lhs = "<localleader>orh", desc = "add/remove ❤️ reaction" },
      react_eyes = { lhs = "<localleader>ore", desc = "add/remove 👀 reaction" },
      react_thumbs_up = { lhs = "<localleader>or+", desc = "add/remove 👍 reaction" },
      react_thumbs_down = { lhs = "<localleader>or-", desc = "add/remove 👎 reaction" },
      react_rocket = { lhs = "<localleader>orr", desc = "add/remove 🚀 reaction" },
      react_laugh = { lhs = "<localleader>orl", desc = "add/remove 😄 reaction" },
      react_confused = { lhs = "<localleader>orc", desc = "add/remove 😕 reaction" },
      review_start = { lhs = "<localleader>ovs", desc = "start a review for the current PR" },
      review_resume = { lhs = "<localleader>ovr", desc = "resume a pending review for the current PR" },
      resolve_thread = { lhs = "<localleader>ort", desc = "resolve PR thread" },
      unresolve_thread = { lhs = "<localleader>orT", desc = "unresolve PR thread" },
    },
    review_thread = {
      goto_issue = { lhs = "<localleader>ogi", desc = "navigate to a local repo issue" },
      add_comment = { lhs = "<localleader>oca", desc = "add comment" },
      add_reply = { lhs = "<localleader>ocr", desc = "add reply" },
      add_suggestion = { lhs = "<localleader>osa", desc = "add suggestion" },
      delete_comment = { lhs = "<localleader>ocd", desc = "delete comment" },
      next_comment = { lhs = "]c", desc = "go to next comment" },
      prev_comment = { lhs = "[c", desc = "go to previous comment" },
      select_next_entry = { lhs = "]q", desc = "move to next changed file" },
      select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
      select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
      select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
      close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
      react_hooray = { lhs = "<localleader>orp", desc = "add/remove 🎉 reaction" },
      react_heart = { lhs = "<localleader>orh", desc = "add/remove ❤️ reaction" },
      react_eyes = { lhs = "<localleader>ore", desc = "add/remove 👀 reaction" },
      react_thumbs_up = { lhs = "<localleader>or+", desc = "add/remove 👍 reaction" },
      react_thumbs_down = { lhs = "<localleader>or-", desc = "add/remove 👎 reaction" },
      react_rocket = { lhs = "<localleader>orr", desc = "add/remove 🚀 reaction" },
      react_laugh = { lhs = "<localleader>orl", desc = "add/remove 😄 reaction" },
      react_confused = { lhs = "<localleader>orc", desc = "add/remove 😕 reaction" },
      resolve_thread = { lhs = "<localleader>ort", desc = "resolve PR thread" },
      unresolve_thread = { lhs = "<localleader>orT", desc = "unresolve PR thread" },
    },
    submit_win = {
      approve_review = { lhs = "<C-a>", desc = "approve review", mode = { "n", "i" } },
      comment_review = { lhs = "<C-m>", desc = "comment review", mode = { "n", "i" } },
      request_changes = { lhs = "<C-r>", desc = "request changes review", mode = { "n", "i" } },
      close_review_tab = { lhs = "<C-c>", desc = "close review tab", mode = { "n", "i" } },
    },
    review_diff = {
      submit_review = { lhs = "<localleader>ovs", desc = "submit review" },
      discard_review = { lhs = "<localleader>ovd", desc = "discard review" },
      add_review_comment = { lhs = "<localleader>oca", desc = "add a new review comment", mode = { "n", "x" } },
      add_review_suggestion = { lhs = "<localleader>osa", desc = "add a new review suggestion", mode = { "n", "x" } },
      focus_files = { lhs = "<localleader>oe", desc = "move focus to changed file panel" },
      toggle_files = { lhs = "<localleader>ob", desc = "hide/show changed files panel" },
      next_thread = { lhs = "]t", desc = "move to next thread" },
      prev_thread = { lhs = "[t", desc = "move to previous thread" },
      select_next_entry = { lhs = "]q", desc = "move to next changed file" },
      select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
      select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
      select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
      close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
      toggle_viewed = { lhs = "<localleader>o<space>", desc = "toggle viewer viewed state" },
      goto_file = { lhs = "gf", desc = "go to file" },
    },
    file_panel = {
      submit_review = { lhs = "<localleader>ovs", desc = "submit review" },
      discard_review = { lhs = "<localleader>ovd", desc = "discard review" },
      next_entry = { lhs = "j", desc = "move to next changed file" },
      prev_entry = { lhs = "k", desc = "move to previous changed file" },
      select_entry = { lhs = "<cr>", desc = "show selected changed file diffs" },
      refresh_files = { lhs = "R", desc = "refresh changed files panel" },
      focus_files = { lhs = "<localleader>oe", desc = "move focus to changed file panel" },
      toggle_files = { lhs = "<localleader>ob", desc = "hide/show changed files panel" },
      select_next_entry = { lhs = "]q", desc = "move to next changed file" },
      select_prev_entry = { lhs = "[q", desc = "move to previous changed file" },
      select_first_entry = { lhs = "[Q", desc = "move to first changed file" },
      select_last_entry = { lhs = "]Q", desc = "move to last changed file" },
      close_review_tab = { lhs = "<C-c>", desc = "close review tab" },
      toggle_viewed = { lhs = "<localleader>o<space>", desc = "toggle viewer viewed state" },
    },
    notification = {
      read = { lhs = "<localleader>onr", desc = "mark notification as read" },
      done = { lhs = "<localleader>ond", desc = "mark notification as done" },
      unsubscribe = { lhs = "<localleader>onu", desc = "unsubscribe from notifications" },
    },
  },
})
